language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: qC60f3nEe7AEw4FnX4ENCuAlhwN+WwaGHZf8seEU2eGhH4oxLpfBg3bETvdtchEKqibF2sb4/7P7uzAn1751RiAur4iUOu2fYw9o+AfiRzIMVvFMgTLttUbAWENPcGoZlSC6k5ckdtHjGvu1jFGgghIh1sFIW9Pe9MObFFXzZf62M6QHwaCobEvszUHkWDZxyfs7MovPjCYiS+UdmQ5bhTJ/ByRc3RSpnJCN5XaOmR9qM5EUvZ58BVckkFDUT7SPjjLKk8oGnVKiCmbTDz7p8pd5mfm/FV4iW73wim0GF50dGiUAdmKHqvyX5ogJobdhW12lG2J6nZrlTTloIVa7kITsyqrLQiHaHhCLSfWLte3rlY6G2a2zXOzqK2ZOdVH2QEwIWkgt79gjyg2+iHfDY0+mC+O2GUEhctpOTp71RZQ7LG9Wb1XA8oAJ9BFg5Xs4LGonl+XagVLPbTaIm7SKTLg85cPl8W3mYB/dRyejZvfAYVLySg2FQauqFB7PDI9jAihnLly1Wwk1XaFNIwGsCQzDNYN4lIXgj5YUf5pnZJQwlE3JN0yB8we6avXijLx3fsz4CC7aakSxyvvk+oSE69X/Url3QcKeXVFpIR5n1O2S15USK4GpTo2BE1qToM7APmuJeCBPplHd53n3RxSwwZ+P7eVvL/0a1WA8DgbE/Zs=
  app: threadert5
  on:
    repo: antalk/threader
env:
  global:
    secure: cNC/ejmrZisaTP4QP7N6j2uMRwMsa6uN65ZxQ3DdXCjTCr5bKxXhfY/FG4YsxJQEst8arEptjIJKu7QEVmhjBp8tDfaRvx9GpBuaS/7Z0lFRkmWEZLPbajm6QjgRG9yyJAuAHydxg3Ss0v2LDrf0nGsMjMSt0DpiXpMQS5wQWbO/QD2FwSym0UFtudVfaB9gQYW8Pla69FERlJzBKqvG21ojpFu0eFjR3fZbVjLdo7gFExVJxDTkydCG7eGodLudT5/H+NlQTa0h7QknSk5M2k2i2OhSjwrgmE0EtvpCLcbntF9cnxtWIOzGpIetT5Vtea5tNk4CscBmeh1S1EPKalJWdMoAoBQfcXJqcrXP4BjsZKQ4B/XJS5CeIv1HZQHFsITZjTbWSbZM++KGgq4Ap0QYKLtkDNKQh2d+Zk0I9P0WoQTDZSNXN4y4L8pRG8r4y8pIEGQ/dys+ak5nXqHEXH/rf3OkMGgMRrkYuwGENApRG3tKA2g0IPg6bOADpHibUuhCbVdYtP15zQ0xT1FOWbKF11tlN+76i2dNwDKamY1m6VR20/BDTVmMbj2VcCGz6sd4ZDz+Kj82tR/H2/1RGIGprEmVEtLhgc/e7vf0D2lqGAwS5NmhDnk2w6UQOo9bY9VwAsEF8HG28b6uXV7oBWoCh3i4oxmp7RalxeCNY24=
script:
  # the following command line builds the project, and then execute the SonarQube analysis
  - mvn clean install sonar:sonar -Dsonar.login=$SONAR_TOKEN